[versions]
slf4j = "2.0.17"
junit = "4.13.2"
jackson = "2.21.0"
jspecify = "1.0.0"
gradle = "9.3.1"

[libraries]
slf4j-api = {group = "org.slf4j", name = "slf4j-api",  version.ref = "slf4j"}
slf4j-simple = {group = "org.slf4j", name = "slf4j-simple",  version.ref = "slf4j"}
junit4 = {group = "junit", name = "junit", version.ref = "junit"}
jspecify-annotations = {group = "org.jspecify", name = "jspecify", version.ref = "jspecify"}
jackson-core = {group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson"}
jackson-databind = {group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson"}
jackson-xml = {group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-xml", version.ref = "jackson"}
jackson-jaxb = {group = "com.fasterxml.jackson.module", name = "jackson-module-jaxb-annotations", version.ref = "jackson"}

[plugins]
git-version = {id = "com.palantir.git-version", version = "4.3.0"}
